[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# stctl
[tasks.stctl]
workspace = false
command = "cargo"
args = ["run", "--bin", "stctl", "--", "${@}"]

[tasks.clippy]
clear = true
workspace = false
script = '''
#!/usr/bin/env bash
set -e

cargo clippy --workspace --all-features -- -D warnings

cargo clippy -p example-fullstack-client -- -D warnings
cargo clippy -p example-fullstack-server -- -D warnings
'''
