---
name: Run Tests & Publishing

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Run Lints
        run: ci/feature-soundness.sh

  rustfmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo +nightly fmt -- --unstable-features

  check-templates:
    name: Check Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: stellation

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo Generate
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate

      - name: Generate Template
        run: |
          cargo generate --path stellation/templates/default \
            --name template-default-generated

      - name: Add Stellation Crates
        run: |
          cargo add -p template-default-generated-api \
            --path ../stellation/crates/stellation-bridge

          cargo add -p template-default-generated-client \
            --path ../stellation/crates/stellation-frontend

          cargo add -p template-default-generated-server \
            --path ../stellation/crates/stellation-backend \
            --features cli

          cargo add -p template-default-generated-view \
            --path ../stellation/crates/stellation-frontend

          cargo add -p template-default-generated-view \
            --path ../stellation/crates/stellation-bridge

          cargo add -p template-default-generated-stctl \
            --path ../stellation/crates/stctl
        working-directory: template-default-generated

      - name: Run Lints
        run: |
          cargo clippy --bin stctl
          cargo clippy --bin template-default-generated-client
          cargo clippy --bin template-default-generated-server
        working-directory: template-default-generated

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs:
      - lint
      - rustfmt
      - check-templates
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Set Git Information
        run: |
          git config --global user.name "Stellation Actions"
          git config --global user.email "actions@stellation.dummy"

      - name: Prepare dry-run Registry
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          cargo install cargo-http-registry

          mkdir -p /tmp/dry-run-registry
          nohup cargo-http-registry /tmp/dry-run-registry &

          echo "CARGO_PUBLISH_EXTRA_ARGS=--registry=dry-run" >> $GITHUB_ENV

          echo "[registries.dry-run]" >> ~/.cargo/config.toml
          echo 'index = "file:///tmp/dry-run-registry"' >> ~/.cargo/config.toml
          echo 'token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"' >> ~/.cargo/config.toml

      - name: Modify to publish to dry-run Registry
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          cargo install toml-cli

          toml set \
            crates/stellation-backend/Cargo.toml \
            dependencies.stellation-bridge.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation-backend/Cargo.toml

          toml set \
            crates/stellation-backend/Cargo.toml \
            dependencies.stellation-core.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation-backend/Cargo.toml

          toml set \
            crates/stellation-frontend/Cargo.toml \
            dependencies.stellation-bridge.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation-frontend/Cargo.toml

          toml set \
            crates/stctl/Cargo.toml \
            dependencies.stellation-core.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stctl/Cargo.toml

          toml set \
            crates/stellation/Cargo.toml \
            dependencies.stellation-core.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation/Cargo.toml

          toml set \
            crates/stellation/Cargo.toml \
            dependencies.stellation-bridge.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation/Cargo.toml

          toml set \
            crates/stellation/Cargo.toml \
            dependencies.stellation-frontend.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation/Cargo.toml

          toml set \
            crates/stellation/Cargo.toml \
            dependencies.stellation-backend.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation/Cargo.toml

          toml set \
            crates/stellation/Cargo.toml \
            dependencies.stctl.registry dry-run > /tmp/tempfile-cargo1
          cat /tmp/tempfile-cargo1 > crates/stellation/Cargo.toml

          git commit -a -m "chore: switch to dry-run registry"

      - name: Prepare crates.io Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "CARGO_PUBLISH_EXTRA_ARGS=--token=${{ secrets.CRATES_IO_TOKEN }}" >> $GITHUB_ENV

      - name: Run cargo publish for stellation-core
        run: |
          cargo publish \
            ${{ env.CARGO_PUBLISH_EXTRA_ARGS }} \
            --manifest-path crates/stellation-core/Cargo.toml
        env:
          RUSTFLAGS: "--cfg releasing"

      - name: Run cargo publish for stellation-bridge
        run: |
          cargo publish \
            ${{ env.CARGO_PUBLISH_EXTRA_ARGS }} \
            --manifest-path crates/stellation-bridge/Cargo.toml
        env:
          RUSTFLAGS: "--cfg releasing"

      - name: Run cargo publish for stellation-backend
        run: |
          cargo publish \
            ${{ env.CARGO_PUBLISH_EXTRA_ARGS }} \
            --manifest-path crates/stellation-backend/Cargo.toml
        env:
          RUSTFLAGS: "--cfg releasing"

      - name: Run cargo publish for stellation-frontend
        run: |
          cargo publish \
            ${{ env.CARGO_PUBLISH_EXTRA_ARGS }} \
            --manifest-path crates/stellation-frontend/Cargo.toml
        env:
          RUSTFLAGS: "--cfg releasing"

      - name: Run cargo publish for stctl
        run: |
          cargo publish \
            ${{ env.CARGO_PUBLISH_EXTRA_ARGS }} \
            --manifest-path crates/stctl/Cargo.toml
        env:
          RUSTFLAGS: "--cfg releasing"

      - name: Run cargo publish for stellation
        run: |
          cargo publish \
            ${{ env.CARGO_PUBLISH_EXTRA_ARGS }} \
            --manifest-path crates/stellation/Cargo.toml
        env:
          RUSTFLAGS: "--cfg releasing"

  publish-templates:
    name: Publish Templates
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    needs:
      - lint
      - rustfmt
      - check-templates
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Read Stellation Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          STELLATION_VER=$(echo '${{ github.ref_name }}' | sed 's/v*//')
          echo "Current version: $STELLATION_VER"

          echo "STELLATION_VER=$STELLATION_VER" >> $GITHUB_ENV

      - name: Set Stellation Target to 'main'
        if: github.ref == 'refs/heads/main'
        run: |
          echo 'variable::set("stellation_target", "main");' >> templates/default/resolve-crates.rhai

      - name: Set Stellation Target to 'release'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo 'variable::set("stellation_target", "release");' >> templates/default/resolve-crates.rhai

      - name: Set Stellation Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo 'variable::set("stellation_release_ver", "${{ env.STELLATION_VER }}");' >> templates/default/resolve-crates.rhai

      - name: Publish Main Templates
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: templates-main
          FOLDER: templates
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "chore: sync template for {sha}"

      - name: Publish Main Templates
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:futursolo/stellation-templates.git
          BRANCH: stellation-main
          FOLDER: templates
          MESSAGE: "chore: sync template for {sha}"
          SSH_PRIVATE_KEY: ${{ secrets.TEMPLATE_DEPLOY_PRIVATE_KEY }}

      - name: Publish Release Templates
        if: startsWith(github.ref, 'refs/tags/')
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: templates
          FOLDER: templates
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "chore: sync template for ${{ github.ref_name }}"

      - name: Publish Release Templates
        if: startsWith(github.ref, 'refs/tags/')
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:futursolo/stellation-templates.git
          BRANCH: main
          FOLDER: templates
          MESSAGE: "chore: sync template for ${{ github.ref_name }}"
          SSH_PRIVATE_KEY: ${{ secrets.TEMPLATE_DEPLOY_PRIVATE_KEY }}
