---
name: Run Tests & Publishing

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Run Lints
        run: ci/feature-soundness.sh

  rustfmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo +nightly fmt -- --unstable-features

  check-templates:
    name: Check Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: stackable

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Cargo Generate
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate

      - name: Generate Template
        run: |
          cargo generate --path stackable/templates/fullstack \
            --name template-fullstack-generated \
            --define stackable_is_main=false \
            --define stackable_is_release=false

      - name: Add Stackable Crates
        run: |
          cargo add -p template-fullstack-generated-api \
            --path ../stackable/crates/stackable-bridge

          cargo add -p template-fullstack-generated-client \
            --path ../stackable/crates/stackable-frontend

          cargo add -p template-fullstack-generated-server \
            --path ../stackable/crates/stackable-backend \
            --features cli

          cargo add -p template-fullstack-generated-view \
            --path ../stackable/crates/stackable-frontend

          cargo add -p template-fullstack-generated-view \
            --path ../stackable/crates/stackable-bridge

          cargo add -p stackctl \
            --path ../stackable/crates/stackable-cli
        working-directory: template-fullstack-generated

      - name: Run Lints
        run: |
          cargo clippy --bin stackctl
          cargo clippy --bin template-fullstack-generated-client
          cargo clippy --bin template-fullstack-generated-server
        working-directory: template-fullstack-generated

  publish-templates:
    name: Publish Templates
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    needs: check-templates
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Read Stackable Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          STACKABLE_VER=$(echo '${{ github.ref_name }}' | sed 's/v0*//')
          echo "Current version: $STACKABLE_VER"

          echo "STACKABLE_VER=$(echo '${{ github.ref_name }}' | sed 's/v0*//')" >> $GITHUB_ENV

      - name: Set Stackable Target to 'main'
        if: github.ref == 'refs/heads/main'
        run: |
          echo 'variable::set("stackable_target", "main");' >> templates/fullstack/resolve-crates.rhai

      - name: Set Stackable Target to 'release'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo 'variable::set("stackable_target", "release");' >> templates/fullstack/resolve-crates.rhai

      - name: Set Stackable Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo 'variable::set("stackable_release_ver", "${{ env.STACKABLE_VER }}");' >> templates/fullstack/resolve-crates.rhai

      - name: Publish Main Templates
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: templates-main
          FOLDER: templates
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release Templates
        if: startsWith(github.ref, 'refs/tags/')
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: templates
          FOLDER: templates
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
